on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3

      - name: 'Login to Docker hub'
        run: docker login --username ${{ sectets.DOCKER_USERNAME }} --password ${{ sectets.DOCKER_TOKEN }}

      

